export const productsAll = [
  {
    productId: 'KB002',
    productName: 'KB 골드 연금',
    description: '연 4.0% 복리, 장기 투자에 적합한 연금 상품',
    prft_year: '4.0',
    endDate: '20300101',
    productSegmentId: 'A',
    customerSegmentId: 'A',
  },
  {
    productId: 'KB004',
    productName: 'KB Star 정기예금 (고객맞춤형)',
    description: '안정적인 고금리, 만기 조절 가능',
    prft_year: '3.8',
    endDate: '20260722',
    productSegmentId: 'S',
    customerSegmentId: 'A',
  },
  {
    productId: 'KB005',
    productName: 'KB 글로벌 채권 펀드',
    description: '선진국 우량 채권에 분산 투자',
    prft_year: '5.1',
    endDate: null,
    productSegmentId: 'G',
    customerSegmentId: 'A',
  },
  {
    productId: 'KB006',
    productName: 'KB 내일로 저축보험',
    description: '비과세 혜택과 안정적인 노후 준비',
    prft_year: '3.2',
    endDate: '20351231',
    productSegmentId: 'S',
    customerSegmentId: 'A',
  },
  {
    productId: 'KB007',
    productName: 'KB 미국 대표주식 ETF',
    description: 'S&P 500 지수를 추종하는 ETF',
    prft_year: '9.5',
    endDate: null,
    productSegmentId: 'G',
    customerSegmentId: 'A',
  },
];
